package GUIs;

import java.awt.Color;
import javax.swing.JLabel;

public class SignUp extends javax.swing.JFrame
{

    /**
     * Creates new form SignUp
     */
    public SignUp()
    {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        Background = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        masterpassword = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        emailadd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        confirmpassword = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        helpbtn = new javax.swing.JButton();
        signupbtnn = new javax.swing.JButton();
        logInLbl = new javax.swing.JLabel();
        emailErrLbl = new javax.swing.JLabel();
        mainErrLbl = new javax.swing.JLabel();
        cpassErrLbl = new javax.swing.JLabel();
        mpassErrLbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vweak1 = new javax.swing.JPanel();
        weak1 = new javax.swing.JPanel();
        okay1 = new javax.swing.JPanel();
        strong1 = new javax.swing.JPanel();
        vstrong1 = new javax.swing.JPanel();
        vweakLbl = new javax.swing.JLabel();
        okayLbl = new javax.swing.JLabel();
        weakLbl = new javax.swing.JLabel();
        vstrongLbl = new javax.swing.JLabel();
        strongLbl = new javax.swing.JLabel();
        testPasswordStrengthBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EN//KRYPT -SIGN UP");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 0, 0));

        Background.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PLEASE CREATE AN ACCOUNT OR ");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MASTER PASSWORD");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EMAIL ADDRESS");

        emailadd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                emailaddActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CONFIRM PASSWORD");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PASSWORD STRENGTH");

        helpbtn.setText("HELP ?");
        helpbtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                helpbtnActionPerformed(evt);
            }
        });

        signupbtnn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        signupbtnn.setText("SIGN UP");
        signupbtnn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                signupbtnnActionPerformed(evt);
            }
        });

        logInLbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        logInLbl.setForeground(new java.awt.Color(204, 204, 204));
        logInLbl.setText("LOG IN");
        logInLbl.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                logInLblMouseClicked(evt);
            }
        });

        emailErrLbl.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        emailErrLbl.setForeground(new java.awt.Color(255, 0, 0));

        mainErrLbl.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        mainErrLbl.setForeground(new java.awt.Color(255, 0, 0));

        cpassErrLbl.setForeground(new java.awt.Color(255, 0, 51));

        mpassErrLbl.setForeground(new java.awt.Color(255, 0, 51));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("WEAK ------------------------------------------------------------------------ STRONG");

        vweak1.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout vweak1Layout = new javax.swing.GroupLayout(vweak1);
        vweak1.setLayout(vweak1Layout);
        vweak1Layout.setHorizontalGroup(
            vweak1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        vweak1Layout.setVerticalGroup(
            vweak1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        weak1.setBackground(new java.awt.Color(255, 102, 51));

        javax.swing.GroupLayout weak1Layout = new javax.swing.GroupLayout(weak1);
        weak1.setLayout(weak1Layout);
        weak1Layout.setHorizontalGroup(
            weak1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        weak1Layout.setVerticalGroup(
            weak1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        okay1.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout okay1Layout = new javax.swing.GroupLayout(okay1);
        okay1.setLayout(okay1Layout);
        okay1Layout.setHorizontalGroup(
            okay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        okay1Layout.setVerticalGroup(
            okay1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        strong1.setBackground(new java.awt.Color(204, 255, 102));

        javax.swing.GroupLayout strong1Layout = new javax.swing.GroupLayout(strong1);
        strong1.setLayout(strong1Layout);
        strong1Layout.setHorizontalGroup(
            strong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        strong1Layout.setVerticalGroup(
            strong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        vstrong1.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout vstrong1Layout = new javax.swing.GroupLayout(vstrong1);
        vstrong1.setLayout(vstrong1Layout);
        vstrong1Layout.setHorizontalGroup(
            vstrong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        vstrong1Layout.setVerticalGroup(
            vstrong1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        vweakLbl.setText("YOURS");

        okayLbl.setText("YOURS");

        weakLbl.setText("YOURS");

        vstrongLbl.setText("YOURS");

        strongLbl.setText("YOURS");

        testPasswordStrengthBtn.setText("TEST");
        testPasswordStrengthBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                testPasswordStrengthBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logInLbl))
                            .addComponent(emailErrLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainErrLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpassErrLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mpassErrLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(confirmpassword, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(masterpassword, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
                            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(emailadd, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(vweak1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(weak1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(okay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(strong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vstrong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel7))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(vweakLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(weakLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(okayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(strongLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(vstrongLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(testPasswordStrengthBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(signupbtnn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(helpbtn)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logInLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailadd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(emailErrLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(masterpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(mpassErrLbl)
                .addGap(3, 3, 3)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cpassErrLbl)
                .addGap(25, 25, 25)
                .addComponent(mainErrLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vweakLbl)
                    .addComponent(okayLbl)
                    .addComponent(weakLbl)
                    .addComponent(strongLbl)
                    .addComponent(vstrongLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vstrong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vweak1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weak1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(strong1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(signupbtnn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(helpbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(testPasswordStrengthBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailaddActionPerformed

    public void setCpassErrLbl(JLabel cpassErrLbl)
    {
        this.cpassErrLbl = cpassErrLbl;
    }

    public void setEmailErrLbl(String s)
    {
        emailErrLbl.setText(s);
    }

    public void setMainErrLbl(JLabel mainErrLbl)
    {
        this.mainErrLbl = mainErrLbl;
    }

    public void setMpassErrLbl(JLabel mpassErrLbl)
    {
        this.mpassErrLbl = mpassErrLbl;
    }

    //clears all error labels
    public void clearErrors()
    {
        emailErrLbl.setText(" ");
        mainErrLbl.setText(" ");
        cpassErrLbl.setText(" ");
        mpassErrLbl.setText(" ");
    }
    //signs the user up and logs them into their dashboard by:
    // - performing a blanck check with respective errors
    // - verifying the login details by : making sure it doesnt already exist
    //                                    the passwords match
                                          
    // - writing the users temporary data into text files by calling the respective methods
    // - setting the header label in the dashboard to the users email
    private void signupbtnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupbtnnActionPerformed
        userFunctions obj = new userFunctions();
        arrUsers arrUserObj = new arrUsers();
        clearErrors();
        String email, mpassword, cpassword;
        email = emailadd.getText();
        mpassword = masterpassword.getText();
        cpassword = confirmpassword.getText();

        if (obj.isFieldBlank(email, mpassword, cpassword))
        {
            mainErrLbl.setText("FIELDS CANNOT BE BLANK");
        }
        if (obj.doesUsernameExist(email))
        {
            emailErrLbl.setText("EMAIL IS ALREADY REGISTERED");
        }
        if (obj.doPasswordsMatch(mpassword, cpassword) == false)
        {
            cpassErrLbl.setText("PASSWORDS DONT MATCH");
        }
        if (obj.verifyDetails(email, mpassword, cpassword))
        {
            Home homeObj = new Home();
            homeObj.setVisible(true);
            this.dispose();
            obj.createUser(email, mpassword);
            obj.signPos(emailadd.getText());
            obj.signUserIn(emailadd.getText());
            arrUserObj.setUserPos(arrUserObj.SearchUsers(emailadd.getText()));
            homeObj.usernamelbl.setText(arrUserObj.arrUsers[obj.getUserPosition()].getEmail());
        }
    }//GEN-LAST:event_signupbtnnActionPerformed

    //displays the help GUI for the Sign Up screen
    private void helpbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpbtnActionPerformed
        HelpSignUp obj = new HelpSignUp();
        obj.setVisible(true);

    }//GEN-LAST:event_helpbtnActionPerformed

    //terminates this screen and displays the logIn screen
    private void logInLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logInLblMouseClicked
        LogIn obj = new LogIn();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logInLblMouseClicked
    //determines and classifies the strenght of the password *refer to algorithm
    private void testPasswordStrengthBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testPasswordStrengthBtnActionPerformed
    {//GEN-HEADEREND:event_testPasswordStrengthBtnActionPerformed
        programmeFunctions obj = new programmeFunctions();
        //clears labels when from preious states
        vstrongLbl.setForeground(Color.BLACK);
        strongLbl.setForeground(Color.BLACK);
        okayLbl.setForeground(Color.BLACK);
        weakLbl.setForeground(Color.BLACK);
        vweakLbl.setForeground(Color.BLACK);

        /*swtich statement which highlights the corresponding jlabel, 
        in order to indicate the passwords strenght*/
        switch (obj.calcStrength(masterpassword.getText()))
        {
            case 5:
                // code block
                vstrongLbl.setForeground(Color.WHITE);
                break;
            case 4:
                // code block
                strongLbl.setForeground(Color.WHITE);
                break;
            case 3:
                // code block
                okayLbl.setForeground(Color.WHITE);
                break;
            case 2:
                // code block
                weakLbl.setForeground(Color.WHITE);
                break;
            case 1:
                // code block
                vweakLbl.setForeground(Color.WHITE);
                break;
            default:
            // code block
        }

    }//GEN-LAST:event_testPasswordStrengthBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JTextField confirmpassword;
    public javax.swing.JLabel cpassErrLbl;
    public javax.swing.JLabel emailErrLbl;
    private javax.swing.JTextField emailadd;
    private javax.swing.JButton helpbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel logInLbl;
    public javax.swing.JLabel mainErrLbl;
    private javax.swing.JTextField masterpassword;
    protected javax.swing.JLabel mpassErrLbl;
    private javax.swing.JPanel okay1;
    private javax.swing.JLabel okayLbl;
    private javax.swing.JButton signupbtnn;
    private javax.swing.JPanel strong1;
    private javax.swing.JLabel strongLbl;
    private javax.swing.JButton testPasswordStrengthBtn;
    private javax.swing.JPanel vstrong1;
    private javax.swing.JLabel vstrongLbl;
    private javax.swing.JPanel vweak1;
    private javax.swing.JLabel vweakLbl;
    private javax.swing.JPanel weak1;
    private javax.swing.JLabel weakLbl;
    // End of variables declaration//GEN-END:variables
}
